import { useLocation } from 'react-router-dom';
import {
	DownloadApp,
	FaqContainer,
	FaqLink,
	FooterAbout,
	FooterAboutCompany,
	FooterAboutImage,
	FooterCompaniesContainer,
	FooterContainer,
	FooterFeaturette,
	FooterRuleRegulations,
	FooterSocials,
	FooterWrapper,
	WhatsApp,
	WhatsappTitle,
} from './Index.styled';
import Icon from '../common/Icon/Index';
import { FC } from 'react';

interface Link {
	label: string;
	address: string;
}

interface Company {
	link: string;
	img: string;

}
interface Props {
	expanded: boolean
}
const Footer: FC<Props> = ({
	expanded
}) => {
	const path = useLocation();
	const restrictedPathNames = ['/signin', '/signup', '/change-password'];
	const shouldRenderFooter = !restrictedPathNames.find(
		p => p === path.pathname
	);

	const companies: Array<Company> = [
		{
			link: '/',
			img: 'upi.svg#upi',
		},
		{
			link: '/',
			img: 'bank-transfer.svg#bank-transfer',
		},
		{
			link: '/',
			img: 'be-gamble.svg#be-gamble',
		},
		{
			link: '/',
			img: 'gambling-commission.svg#gambling-commission',
		},
		{
			link: '/',
			img: 'e-cogra.svg#e-cogra',
		},
		{
			link: '/',
			img: 'mga.svg#mga',
		},
	];

	const links: Array<Link> = [
		{
			label: 'Introduction',
			address: '/introduction',
		},
		{
			label: 'How to register',
			address: '/how-to-register',
		},
		{
			label: 'How to deposit',
			address: '/hot-to-deposit',
		},
		{
			label: 'How to use bonus',
			address: '/how-to-use-bonus',
		},
	];

	return !shouldRenderFooter ? null : (
		<FooterContainer aria-expanded={expanded}>
			<FooterWrapper>
				<DownloadApp className='download'>
					<Icon
						width='auto'
						isSvgIcon
						src='/assets/icons/footer/download-app.svg#download-app'
					/>
				</DownloadApp>

				<FaqContainer className='faq-container'>
					{links.map(link => (
						<FaqLink key={link.label} to={link.address}>
							{link.label}
						</FaqLink>
					))}
				</FaqContainer>

				<WhatsApp>
					<Icon
						width='4rem'
						src='/assets/icons/socials/whatsapp.svg#whatsapp'
						isSvgIcon
					/>
					<WhatsappTitle>WhatsApp Now!</WhatsappTitle>
				</WhatsApp>

				<FooterFeaturette>
					<FooterSocials className='footer-social'>
						<img src='/assets/icons/socials/instagram.svg' alt='' />
						<img src='/assets/icons/socials/telegram.svg' alt='' />
					</FooterSocials>

					<FooterAbout>
						<FooterAboutImage src='/assets/images/company.png' />
						<FooterAboutCompany>
							LOTUS 365 is a limited liability company incorporated under the
							laws of Curacao Players are requested not to contact any untrusted
							sources for LOTUS 365 accounts as this is an online site and they
							can only register independently without any agents. Only deposit
							through the account details generated by the system or provided by
							our official support team
						</FooterAboutCompany>
					</FooterAbout>

					<FooterCompaniesContainer className='footer-companies'>
						{companies.map(company => (
							<Icon
								key={company.img}
								isSvgIcon={false}
								width='100px'
								src={`/assets/icons/footer/${company.img}`}
							/>
						))}
					</FooterCompaniesContainer>
				</FooterFeaturette>

				<FooterRuleRegulations>
					Rules & Regulations &copy; 2016-2022 v. 9.91
				</FooterRuleRegulations>
			</FooterWrapper>
		</FooterContainer>
	);
};

export default Footer;
